"""remove_parent_id_foreign_key_constraint

Revision ID: 211639633107
Revises: ecd991cc3c39
Create Date: 2025-10-20 19:01:54.719839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211639633107'
down_revision = 'ecd991cc3c39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
