"""remove_parent_table_allow_anonymous_appointments

Revision ID: ecd991cc3c39
Revises: add_child_info_001
Create Date: 2025-10-20 18:44:03.343501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd991cc3c39'
down_revision = 'add_child_info_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint from appointments to parents
    op.drop_constraint('appointments_parent_id_fkey', 'appointments', type_='foreignkey')
    
    # Drop the parents table
    op.drop_table('parents')
    
    op.alter_column('appointments', 'child_name',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'child_year',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('appointments', 'child_class',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recreate the parents table
    op.create_table('parents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('student_class', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_user_id'), 'parents', ['user_id'], unique=False)
    
    # Recreate foreign key constraint from appointments to parents
    op.create_foreign_key('appointments_parent_id_fkey', 'appointments', 'parents', ['parent_id'], ['id'])
    
    op.alter_column('appointments', 'child_class',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('appointments', 'child_year',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.alter_column('appointments', 'child_name',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
