version: '3.8'

# Development Docker Compose Configuration
# Usage: docker-compose -f deployment/docker-compose.dev.yml up -d

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: school-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-schooladmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpassword123}
      POSTGRES_DB: ${POSTGRES_DB:-school_appointments}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: school-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_dev_data:
  redis_dev_data:
